format_version: v1.0
type: UniqueComponent
attributes: {id: drvPic32mEthmac}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_ETHMAC_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPic32mEthmac, value: '6528'}
  - type: String
    attributes: {id: DRV_INTMAC_PHY_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPic32mEthmac, value: LAN8740}
  - type: Boolean
    attributes: {id: TCPIP_EMAC_ETH_FILTER_UCAST_OTHER_ACCEPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: ETHMAC_PHY_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvExtPhyLan8740}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: libdrvExtPhyLan8740}
  - type: DirectCapability
    attributes: {id: libdrvPic32mEthmac}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tcpipNetConfig_1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NETCONFIG_MAC_Dependency}
- type: ElementPosition
  attributes: {x: '486', y: '457', id: drvPic32mEthmac}
